### ISSUE TITLE
As a user, I want my query response as a Pandas DataFrame

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/peppi#57]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User

### 💪 Motivation

...so that I can easily display and access the metadata for a specific query

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
O made the development this morning to migrate the messenger notebook that was developed earlier with peppy. The PR should be out shortly.
