### ISSUE TITLE
As a user, I want to read all tables within a collection into a pandas DataFrame

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/peppi#61]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Data User

### 💪 Motivation

...so that I can do my analysis

### 📖 Additional Details

Follow-on to #60

### Acceptance Criteria

**Given** Collection `urn:nasa:pds:mess-rs-raw:data-rsr`
**When I perform** a loop through all members of the collection, and use pds4_tools to read the data products
**Then I expect** the table data to be loaded into a DataFrame

### ⚙️ Engineering Details

See #60 for details

**Comment by tloubrieu-jpl** [comment]
I made that development this morning. I will make a PR shortly.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl I think this was completed for the AGU testing?

**Comment by jordanpadams** [comment]
Closed https://github.com/NASA-PDS/peppi/pull/65
